/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MagazinesIndexRouteImport } from './routes/magazines.index'
import { Route as IndustryIndexRouteImport } from './routes/industry.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MagazinesIdRouteImport } from './routes/magazines.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBacklinksRouteImport } from './routes/admin.backlinks'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as IndustrySlugIndexRouteImport } from './routes/industry.$slug.index'
import { Route as AdminMagazinesIndexRouteImport } from './routes/admin.magazines.index'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin.articles.index'
import { Route as IndustrySlugSubRouteImport } from './routes/industry.$slug.$sub'
import { Route as AdminMagazinesNewRouteImport } from './routes/admin.magazines.new'
import { Route as AdminMagazinesIdRouteImport } from './routes/admin.magazines.$id'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as AdminArticlesIdRouteImport } from './routes/admin.articles.$id'

const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazinesIndexRoute = MagazinesIndexRouteImport.update({
  id: '/magazines/',
  path: '/magazines/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryIndexRoute = IndustryIndexRouteImport.update({
  id: '/industry/',
  path: '/industry/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazinesIdRoute = MagazinesIdRouteImport.update({
  id: '/magazines/$id',
  path: '/magazines/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBacklinksRoute = AdminBacklinksRouteImport.update({
  id: '/admin/backlinks',
  path: '/admin/backlinks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySlugIndexRoute = IndustrySlugIndexRouteImport.update({
  id: '/industry/$slug/',
  path: '/industry/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMagazinesIndexRoute = AdminMagazinesIndexRouteImport.update({
  id: '/admin/magazines/',
  path: '/admin/magazines/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/admin/articles/',
  path: '/admin/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySlugSubRoute = IndustrySlugSubRouteImport.update({
  id: '/industry/$slug/$sub',
  path: '/industry/$slug/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMagazinesNewRoute = AdminMagazinesNewRouteImport.update({
  id: '/admin/magazines/new',
  path: '/admin/magazines/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMagazinesIdRoute = AdminMagazinesIdRouteImport.update({
  id: '/admin/magazines/$id',
  path: '/admin/magazines/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/admin/articles/new',
  path: '/admin/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/admin/articles/$id',
  path: '/admin/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/newsletter': typeof NewsletterRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/backlinks': typeof AdminBacklinksRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/magazines/$id': typeof MagazinesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/industry/': typeof IndustryIndexRoute
  '/magazines/': typeof MagazinesIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/magazines/$id': typeof AdminMagazinesIdRoute
  '/admin/magazines/new': typeof AdminMagazinesNewRoute
  '/industry/$slug/$sub': typeof IndustrySlugSubRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/magazines/': typeof AdminMagazinesIndexRoute
  '/industry/$slug/': typeof IndustrySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/newsletter': typeof NewsletterRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/backlinks': typeof AdminBacklinksRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/magazines/$id': typeof MagazinesIdRoute
  '/admin': typeof AdminIndexRoute
  '/industry': typeof IndustryIndexRoute
  '/magazines': typeof MagazinesIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/magazines/$id': typeof AdminMagazinesIdRoute
  '/admin/magazines/new': typeof AdminMagazinesNewRoute
  '/industry/$slug/$sub': typeof IndustrySlugSubRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/magazines': typeof AdminMagazinesIndexRoute
  '/industry/$slug': typeof IndustrySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/newsletter': typeof NewsletterRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/backlinks': typeof AdminBacklinksRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/magazines/$id': typeof MagazinesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/industry/': typeof IndustryIndexRoute
  '/magazines/': typeof MagazinesIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/magazines/$id': typeof AdminMagazinesIdRoute
  '/admin/magazines/new': typeof AdminMagazinesNewRoute
  '/industry/$slug/$sub': typeof IndustrySlugSubRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/magazines/': typeof AdminMagazinesIndexRoute
  '/industry/$slug/': typeof IndustrySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/awards'
    | '/contact'
    | '/newsletter'
    | '/admin/activity'
    | '/admin/backlinks'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/subscribers'
    | '/admin/users'
    | '/article/$slug'
    | '/category/$slug'
    | '/magazines/$id'
    | '/admin/'
    | '/industry/'
    | '/magazines/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/magazines/$id'
    | '/admin/magazines/new'
    | '/industry/$slug/$sub'
    | '/admin/articles/'
    | '/admin/magazines/'
    | '/industry/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/awards'
    | '/contact'
    | '/newsletter'
    | '/admin/activity'
    | '/admin/backlinks'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/subscribers'
    | '/admin/users'
    | '/article/$slug'
    | '/category/$slug'
    | '/magazines/$id'
    | '/admin'
    | '/industry'
    | '/magazines'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/magazines/$id'
    | '/admin/magazines/new'
    | '/industry/$slug/$sub'
    | '/admin/articles'
    | '/admin/magazines'
    | '/industry/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles'
    | '/awards'
    | '/contact'
    | '/newsletter'
    | '/admin/activity'
    | '/admin/backlinks'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/subscribers'
    | '/admin/users'
    | '/article/$slug'
    | '/category/$slug'
    | '/magazines/$id'
    | '/admin/'
    | '/industry/'
    | '/magazines/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/magazines/$id'
    | '/admin/magazines/new'
    | '/industry/$slug/$sub'
    | '/admin/articles/'
    | '/admin/magazines/'
    | '/industry/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRoute
  AwardsRoute: typeof AwardsRoute
  ContactRoute: typeof ContactRoute
  NewsletterRoute: typeof NewsletterRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminBacklinksRoute: typeof AdminBacklinksRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  MagazinesIdRoute: typeof MagazinesIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  IndustryIndexRoute: typeof IndustryIndexRoute
  MagazinesIndexRoute: typeof MagazinesIndexRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminMagazinesIdRoute: typeof AdminMagazinesIdRoute
  AdminMagazinesNewRoute: typeof AdminMagazinesNewRoute
  IndustrySlugSubRoute: typeof IndustrySlugSubRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminMagazinesIndexRoute: typeof AdminMagazinesIndexRoute
  IndustrySlugIndexRoute: typeof IndustrySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazines/': {
      id: '/magazines/'
      path: '/magazines'
      fullPath: '/magazines/'
      preLoaderRoute: typeof MagazinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/': {
      id: '/industry/'
      path: '/industry'
      fullPath: '/industry/'
      preLoaderRoute: typeof IndustryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazines/$id': {
      id: '/magazines/$id'
      path: '/magazines/$id'
      fullPath: '/magazines/$id'
      preLoaderRoute: typeof MagazinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backlinks': {
      id: '/admin/backlinks'
      path: '/admin/backlinks'
      fullPath: '/admin/backlinks'
      preLoaderRoute: typeof AdminBacklinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/$slug/': {
      id: '/industry/$slug/'
      path: '/industry/$slug'
      fullPath: '/industry/$slug/'
      preLoaderRoute: typeof IndustrySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/magazines/': {
      id: '/admin/magazines/'
      path: '/admin/magazines'
      fullPath: '/admin/magazines/'
      preLoaderRoute: typeof AdminMagazinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/admin/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/$slug/$sub': {
      id: '/industry/$slug/$sub'
      path: '/industry/$slug/$sub'
      fullPath: '/industry/$slug/$sub'
      preLoaderRoute: typeof IndustrySlugSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/magazines/new': {
      id: '/admin/magazines/new'
      path: '/admin/magazines/new'
      fullPath: '/admin/magazines/new'
      preLoaderRoute: typeof AdminMagazinesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/magazines/$id': {
      id: '/admin/magazines/$id'
      path: '/admin/magazines/$id'
      fullPath: '/admin/magazines/$id'
      preLoaderRoute: typeof AdminMagazinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/admin/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/admin/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRoute,
  AwardsRoute: AwardsRoute,
  ContactRoute: ContactRoute,
  NewsletterRoute: NewsletterRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminBacklinksRoute: AdminBacklinksRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminUsersRoute: AdminUsersRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  MagazinesIdRoute: MagazinesIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  IndustryIndexRoute: IndustryIndexRoute,
  MagazinesIndexRoute: MagazinesIndexRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminMagazinesIdRoute: AdminMagazinesIdRoute,
  AdminMagazinesNewRoute: AdminMagazinesNewRoute,
  IndustrySlugSubRoute: IndustrySlugSubRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminMagazinesIndexRoute: AdminMagazinesIndexRoute,
  IndustrySlugIndexRoute: IndustrySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
